article: deploying k3s with command package
pulumi/pulumi-hugo pull request #1028
Opened 2022-02-02 19:36 UTC by rawkode

2022-02-02 19:45 UTC, katcosgrove approved these changes
no nits, looks good to me!

2022-02-02 20:00 UTC, nimbinatus requested changes
Couple metadata patches to make sure it publishes and a question or two, but looks great!

2022-02-03 22:15 UTC, rawkode commented on themes/default/content/blog/deploying-k3s-with-command-package/index.md
> +```ts
Yeah, the how-to will have all the examples. When it's ready, I'll loop back and link from here

2022-02-03 23:37 UTC, nimbinatus approved these changes
Love the image! I'm gonna approve here to unblock; I suspect the docs build will fail because the links in paragraph one aren't relrefs, but let's find out if they have to be :)

2022-02-03 23:53 UTC, merged