Add information about "profile" param in state backend
pulumi/pulumi-hugo pull request #1522
Opened 2022-05-18 08:52 UTC by ekini

Oh, I've been wanting to do this for almost a year!

Depends on the unreleased version of the cli.
After that's released with the updated go-cloud library, it'll become a breeze to work on multiple projects on AWS without thinking about env vars.

Even though we have a workaround of using direnv to set the `AWS_PROFILE`, this new approach is much cleaner and consistent across multiple people.

This PR is a sibling of #1499, which covers the encryption part.

2022-05-20 15:22 UTC, jkodroff requested changes
Suggested changes for spelling mistake, simplified language.

2022-05-20 15:22 UTC, jkodroff commented on themes/default/content/docs/intro/concepts/state.md
> +Alternatively, there are 2 other options that help to aboid needing to type it every time:
```suggestion
Alternatively, there are 2 other options that avoid the need to type it every time:
```

2022-05-20 15:22 UTC, jkodroff commented on themes/default/content/docs/intro/concepts/state.md
> +Additionally, as of Pulumi CLI v3.32.2, it's possible to specify AWS profile from the shared config file `~/.aws/config` in the URL query parameter, i.e. `s3://<bucket-name>?profile=main`
```suggestion
As of Pulumi CLI v3.32.2, it's possible to specify AWS profile from the shared config file `~/.aws/config` in the URL query parameter, i.e. `s3://<bucket-name>?profile=main`
```

2022-05-20 15:23 UTC, susanev commented
@ekini thank you for opening a pr!! would you be up for accepting @jkodroff's changes before we merge this?

2022-05-22 07:21 UTC, ekini commented
Thank you! Should be all fixed, along with the freshly released 3.33.1 version.

2022-05-22 13:29 UTC, susanev approved these changes

2022-05-22 15:35 UTC, merged