Update next-steps.md
pulumi/pulumi-hugo pull request #1587
Opened 2022-06-06 19:01 UTC by aaronkao

2022-06-06 19:33 UTC, nimbinatus requested changes
Some notes; the links are broken because of the trailing slashes.

2022-06-06 19:33 UTC, nimbinatus commented on themes/default/content/docs/get-started/aws/next-steps.md
> +You can go through our Learn tutorials to have a comprehensive walkthrough of the key Pulumi concepts taught through the context of a real-life application.
```suggestion
## Learn Pulumi

You can go through our Learn tutorials to have a comprehensive walkthrough of the key Pulumi concepts taught through the context of a real-life application.
```

2022-06-06 19:33 UTC, nimbinatus commented on themes/default/content/docs/get-started/aws/next-steps.md
> +    <a class="btn btn-lg mx-1 my-1" href="{{< relref "/learn/pulumi-fundamentals/" >}}">Learn Pulumi Fundamentals</a>
It's better to only have one button of a primary color per page (one primary CTA) to help the user with other buttons being in secondary colors/secondary button types. Did the layout go through UX?

2022-06-06 19:33 UTC, nimbinatus commented on themes/default/content/docs/get-started/aws/next-steps.md
> +You can go through our How-To Guides if there is a specific application stack or architecture that you wanted to deploy. These guides come in all the Pulumi languages and cover many common architectu
```suggestion
## How-to Guides

You can go through our How-To Guides if there is a specific application stack or architecture that you want to deploy. These guides come in all the Pulumi languages and cover many common architectures such as [static websites]({{< relref "/registry/packages/aws-native/how-to-guides/aws-native-ts-s3-folder" >}}), [EC2 virtual machines]({{< relref "/registry/packages/aws/how-to-guides/ec2-webserver" >}}), [EKS clusters]({{< relref "/registry/packages/aws/how-to-guides/aws-ts-eks" >}}), [Fargate containers]({{< relref "/registry/packages/aws/how-to-guides/ecs-fargate" >}}), and [serverless applications]({{< relref "/registry/packages/aws/how-to-guides/rest-api" >}}). 
```

2022-06-06 19:33 UTC, nimbinatus commented on themes/default/content/docs/get-started/aws/next-steps.md
> +    <a class="btn btn-lg mx-1 my-1" href="{{< relref "/registry/packages/aws/how-to-guides" >}}">Explore How-to Guides</a>
Same note about buttons

2022-06-06 19:33 UTC, nimbinatus commented on themes/default/content/docs/get-started/aws/next-steps.md
> +You can read through our documentation that explains how Pulumi works from its architecture to key concepts, including [stacks]({{< relref "/docs/intro/concepts/stack" >}}), [state]({{< relref "/docs
```suggestion
## How Pulumi Works

You can read through our documentation that explains how Pulumi works from its architecture to key concepts, including [stacks]({{< relref "/docs/intro/concepts/stack" >}}), [state]({{< relref "/docs/intro/concepts/state" >}}), and [secrets]({{< relref "/docs/intro/concepts/secrets" >}}).
```

2022-06-06 19:33 UTC, nimbinatus commented on themes/default/content/docs/get-started/aws/next-steps.md
> +    <a class="btn btn-lg mx-1 my-1" href="{{< relref "/docs/intro/concepts/" >}}">Read Documentation</a>
Same note

2022-06-06 19:33 UTC, nimbinatus commented on themes/default/content/docs/get-started/aws/next-steps.md
> +You can read through the latest blog posts about AWS that discuss everything from new AWS features and products supported by Pulumi to technical AWS architecture best practices.
```suggestion
## Blog Posts

You can read through the latest blog posts about AWS that discuss everything from new AWS features and products supported by Pulumi to technical AWS architecture best practices. 
```

2022-06-06 19:33 UTC, nimbinatus commented on themes/default/content/docs/get-started/aws/next-steps.md
> +    <a class="btn btn-lg mx-1 my-1" href="{{< relref "/blog/tag/aws/" >}}">Read the Pulumi Blog</a>
Same note about the buttons

```suggestion
    <a class="btn btn-lg mx-1 my-1" href="{{< relref "/blog/tag/aws" >}}">Read the Pulumi Blog</a>
```

2022-06-08 21:36 UTC, aaronkao commented on themes/default/content/docs/get-started/aws/next-steps.md
> +Congrats! You have deployed your first project on AWS with Pulumi. Here are the next steps:
Should probably be "Here are the next steps depending on your learning style:"

2022-06-28 16:34 UTC, closed without merging