fix 404 in lambda authorizers blog
pulumi/pulumi-hugo pull request #1605
Opened 2022-06-09 15:48 UTC by susanev

2022-06-09 16:16 UTC, kimberleyamackenzie approved these changes

2022-06-09 16:18 UTC, cnunciato commented on themes/default/content/blog/protecting-your-apis-with-lambda-authorizers-and-pulumi/index.md
> +[Pulumi and Lambda authorizers](https://github.com/pulumi/pulumi-awsx/tree/master/awsx-classic/apigateway#lambda-authorizers).
Do we need to remove the "learn more about" language?

```suggestion
[Learn more about Pulumi and Lambda authorizers](https://github.com/pulumi/pulumi-awsx/tree/master/awsx-classic/apigateway#lambda-authorizers).
```

2022-06-09 16:21 UTC, cnunciato requested changes
The link fix is correct, this is how things read with this change:

![image](https://user-images.githubusercontent.com/274700/172896200-3863b523-c14e-4dfc-bb5e-ddceb03b7947.png)

Can we find a way to keep the "learn more" language?

2022-06-09 17:14 UTC, susanev commented
@cnunciato feel free to push a commit

2022-06-10 15:22 UTC, cnunciato approved these changes
Added a few words -- feel free to merge if you're okay with them!

2022-06-10 17:15 UTC, merged