Add aws serverless application template page
pulumi/pulumi-hugo pull request #1943
Opened 2022-09-14 21:42 UTC by gthuang

Initial draft of the aws-serverless template

2022-09-14 21:49 UTC, cnunciato commented
@gthuang looks like you need a file at `themes/default/content/templates/serverless-application/_index.md`, as I'm not seeing anything on the home page. You should be able to copy the one out of `static-website` and use that as a basis.

2022-09-19 22:53 UTC, lindsaymarolich commented
We are targeting the keyword aws serverless for the [aws template here](http://pulumi-hugo-origin-pr-1943-9f44a1ee.s3-website.us-west-2.amazonaws.com/templates/serverless-application/aws/). That keyword is used throughout and also in the meta title and description. We will have 97th review this for any additional optimization once it is published, but looks to include the recommendations they provided. @SaraDPH for visibility.

2022-09-19 23:21 UTC, cnunciato commented on themes/default/content/templates/serverless-application/aws/index.md
> +## Next steps
This section can all be deleted.

2022-09-19 23:24 UTC, aaronkao reviewed
Some feedback on the landing page

2022-09-19 23:24 UTC, aaronkao commented on themes/default/content/templates/serverless-application/aws/index.md
> +
These needs to be removed since the templates don't have these yet

2022-09-19 23:24 UTC, aaronkao commented on themes/default/content/templates/serverless-application/aws/index.md
> +* Discover more architecture templates as they're available in [Templates &rarr;]({{< relref "/templates" >}})
I don't like this as they are available because youa re gonna have to go back and clean it. With these publishing there will be 5 of them

2022-09-19 23:24 UTC, aaronkao commented on themes/default/content/templates/serverless-application/aws/index.md
> +* Expand your understanding of how Pulumi works in [Architecture &amp; Concepts &rarr;]({{< relref "/docs/intro/concepts" >}})
I really don't think this is a good CTA. You should direct them over to Pulumi Learn pathways

2022-09-19 23:29 UTC, aaronkao commented on themes/default/content/templates/serverless-application/aws/index.md
> +* Read up on the latest new features [in the Pulumi Blog &rarr;]({{< relref "/blog" >}})
I would link to the serverless tag within the blog if you can

2022-09-20 17:30 UTC, cnunciato commented on themes/default/content/templates/serverless-application/aws/index.md
> +---
```suggestion
template:
    prefix: container-aws
---
```

2022-09-20 23:07 UTC, aaronkao requested changes
Some more comments specifically about how we define serverless

2022-09-20 23:07 UTC, aaronkao commented on themes/default/content/templates/serverless-application/_index.md
> +[Serverless](/serverless) applications are scalable, highly available web backends and APIs that use managed services like Function as a Service (FaaS). Serverless computing enables you to build and
```suggestion
### What are serverless applications?

[Serverless](/serverless) applications use cloud services that feature automatic scaling, built-in high availability, and pay-for-use billing models, allowing you to build and run applications without having to provision, scale, and manage any servers yourself.
```

2022-09-20 23:07 UTC, aaronkao commented on themes/default/content/templates/serverless-application/aws/index.md
> +The AWS Serverless Application template deploys a serverless website to AWS that displays the current time. It uses an [Amazon S3 bucket]({{< relref "/registry/packages/aws/api-docs/s3/bucket" >}}) f
```suggestion
The AWS Serverless Application template deploys a serverless website to AWS that displays the current time. It deploys an [Amazon S3 bucket]({{< relref "/registry/packages/aws/api-docs/s3/bucket" >}}) for hosting a static website, an [AWS Lambda function]({{< relref "/registry/packages/aws/api-docs/lambda/function" >}}) that calculates the current time, and an [Amazon API Gateway REST API]({{< relref "/registry/packages/aws/api-docs/apigateway/restapi" >}}) that routes requests to HTML content and the Lambda function. The template also ships with placeholder web content to give you a working Pulumi project out of the box that you can customize easily and extend to suit your needs.
```

2022-09-20 23:33 UTC, aaronkao approved these changes
I think we are good to go to merge after this one change

2022-09-20 23:33 UTC, aaronkao commented on themes/default/content/templates/serverless-application/aws/index.md
> +To use this template to deploy your own AWS serverless infrastructure, make sure you've [installed Pulumi]({{< relref "/docs/get-started/install" >}}) and [configured your AWS credentials]({{< relref
Is there a reason you randomly switched to infrastructure?

```suggestion
To use this template to deploy your own AWS serverless application, make sure you've [installed Pulumi]({{< relref "/docs/get-started/install" >}}) and [configured your AWS credentials]({{< relref "/registry/packages/aws/installation-configuration" >}}), then create a new [project]({{< relref "/docs/intro/concepts/project" >}}) using the template in your language of choice.
```

2022-09-20 23:42 UTC, merged