Kubernetes web app template page
pulumi/pulumi-hugo pull request #2159
Opened 2022-10-31 22:27 UTC by gthuang

Adding landing page for new k8s deployment+service template.

2022-10-31 22:28 UTC, gthuang commented
@cnunciato how do we change the right-side section that says "This template is also available for:"? It currently lists the kubernetes cluster templates, but it doesn't make sense to do that for this page.

2022-11-01 16:17 UTC, scottslowe requested changes
Looks great overall, just a few minor changes needed. Thanks for putting this together!

2022-11-01 16:17 UTC, scottslowe commented on themes/default/content/templates/kubernetes/webapp/index.md
> +Output values like these are useful in many ways, most commonly as inputs for other stacks or related cloud resources. The computed `serviceName`, for example, can be used from the command line to op
Unfortunately, you can't use the computed `serviceName` output in this way. Although it is exposed as a Service, it's not consumable using that URL.

2022-11-01 16:17 UTC, scottslowe commented on themes/default/content/templates/kubernetes/webapp/index.md
> +webserverconfig
This isn't exposed as a configuration setting.

2022-11-01 16:17 UTC, scottslowe commented on themes/default/content/templates/kubernetes/webapp/index.md
> +webserverdeployment
Same here---this isn't exposed as a configuration setting.

2022-11-01 16:31 UTC, scottslowe commented
@gthuang Regarding the use of `serviceName`: we _could_ put in the text that users could port-forward to that Service for testing/verification. I can provide more details if you all think that might be helpful.

2022-11-01 22:50 UTC, scottslowe requested changes
One minor nit regarding an addition, but LGTM otherwise

2022-11-01 22:50 UTC, scottslowe commented on themes/default/content/templates/kubernetes/webapp/index.md
> +You can change the behavior of the Deployment by passing values to it and an example is already included in the template. Projects created with the Kubernetes Application template expose the followin
I don't think I agree with this addition as it isn't really accurate.

2022-11-02 02:16 UTC, scottslowe approved these changes

2022-11-02 02:19 UTC, cnunciato approved these changes

2022-11-02 04:44 UTC, merged