Helm chart template landing page
pulumi/pulumi-hugo pull request #2167
Opened 2022-11-01 22:30 UTC by gthuang

new page

2022-11-01 22:46 UTC, scottslowe requested changes
Only a few small changes. Also, I noted that the right-hand column says that the template is also available for AWS and Azure, which doesn't seem right, so we should look into that.

2022-11-01 22:46 UTC, scottslowe commented on themes/default/content/templates/kubernetes/helm/index.md
> +The Helm Chart template creates an infrastructure as code project in your favorite language that deploys a Helm chart to an existing cluster using Pulumi. It uses Pulumi's [Native Kubernetes Provider
I would change "deploys a web application" to "deploys an application (in this case, the Nginx ingress controller)"

2022-11-01 22:46 UTC, scottslowe commented on themes/default/content/templates/kubernetes/helm/index.md
> +You can change the behavior of the Helm chart by passing values to it and an example is already included in the template. Projects created with the Helm Chart template expose the following [configura
I'd suggest moving this first sentence into a separate paragraph after the last code block in this section (before the "Tidying up") header. 

Also, I'd reword it to something like: "Further customization of the Helm chart itself is accomplished by passing values to the Helm chart in your Pulumi code. An example of passing a few values to the Helm chart is already included in the template for easy reference." (or similar)

2022-11-02 02:14 UTC, scottslowe approved these changes

2022-11-02 02:14 UTC, cnunciato approved these changes
Looks good! Only one little thing I noticed. Feel free to merge once the diagrams are in place and https://github.com/pulumi/templates/pull/439 has been merged as well.

2022-11-02 02:14 UTC, cnunciato commented on themes/default/content/templates/kubernetes-application/_index.md
> +meta_desc: Pulumi program templates that make it easy to deploy kubernetes applications on AWS, Azure, or Google Cloud Platform.
```suggestion
meta_desc: Pulumi program templates that make it easy to deploy Kubernetes applications on AWS, Azure, or Google Cloud Platform.
```

2022-11-02 05:00 UTC, merged