Adding AI challenge
pulumi/pulumi-hugo pull request #2708
Opened 2023-04-14 23:15 UTC by aaronkao

## Description
New challenge for Pulumi AI

2023-04-20 16:06 UTC, scottslowe commented
@aaronkao Is the purpose of this challenge to have folks walk along with the example provided in the blog post, or to create their own unique PulumiAI-generated program?

2023-04-20 18:14 UTC, scottslowe requested changes
I added some suggested changes here and there to help make it clearer that we're showing an example of how they could use Pulumi AI to complete the challenge.

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +There are two ways to complete this challenge:  using the Pulumi AI website or the CLI. We will be using the Pulumi AI website to generate a Pulumi program and then the Pulumi CLI to run the program
```suggestion
There are two ways to complete this challenge: using the Pulumi AI website or the CLI. For this example of doing the challenge, we will be using the Pulumi AI website to generate a Pulumi program, and then using the Pulumi CLI to run the generated program. If you plan to use the CLI, though, you will need to export your cloud provider (we'll use AWS in this example) and OpenAI credentials. To access your OpenAI credentials, go to [__API Keys__ tab](https://platform.openai.com/account/api-keys) in the OpenAI platform console. Then click `Create new secret key` .
```

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +Next, you are going to use Pulumi AI to generate a program that will provision some database infrastructure that will be used for a real-time application that generates lots of data. Using the chat w
```suggestion
Next, you will use Pulumi AI to generate a program that will provision cloud infrastructure. In this example, we'll ask Pulumi AI to create some database infrastructure that will be used for a real-time application that generates lots of data. Using the chat widget on the Pulumi AI page, you'll describe the infrastructure you would like to build. In our case, we supplied: `Deploy a Kinesis Data Stream, RDS database, DynamoDB database, and Timestream database.`
```

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +Copy the Pulumi AI generated program into `__main__.py`. Save the program and then run `pulumi up`. There will be an error that looks like:
```suggestion
Copy the Pulumi AI generated program into `__main__.py`. Save the program and then run `pulumi up`. If your `pulumi up` operation succeeds, then you're done! (Maybe try it again with something more complex?) In our case, there is an error:
```

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +Pulumi AI programs will sometimes have errors, but you can ask it to fix the error. Go back to [pulumi.com/ai](https://pulumi.com/ai) and enter in the chat widget `Fix this error <error outputted fro
```suggestion
Your Pulumi AI-generated program may not work when you run `pulumi up` the first time (like ours), but you can ask it to fix the error. It's OK to have Pulumi AI fix an error as part of the GPT your IaC Challenge. Go back to [pulumi.com/ai](https://pulumi.com/ai) and enter in the chat widget `Fix this error <error output from pulumi up>`
```

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +Pulumi AI will return back the original program with the error corrected, which is including the `database_name` parameter.
```suggestion
Pulumi AI will return back the original program with the error corrected, which in our example now includes the previously-missing `database_name` parameter.
```

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +Take this new code and update `__main__.py`.
```suggestion
You can take the new code generated by Pulumi AI and add it to your program. In our case, we'll use this new code to update `__main__.py`.
```

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +Now that the code is fixed, run `pulumi up` again. This time the program will execute successfully.
```suggestion
Now that the code is fixed, you can run `pulumi up` again. When we ran `pulumi up` again, our program executed successfully.
```

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +You now have important database infrastructure provisioned for your new app.
```suggestion
There you go! Pulumi AI has helped us generate a program to provision important database infrastructure for our new app. What did Pulumi AI generate for you?
```

2023-04-20 18:14 UTC, scottslowe commented on themes/default/content/challenge/ai-architecture.md
> +In this challenge, you have learned how to use Pulumi AI to generate a Pulumi program. This program provisions a Kinesis Data Stream, RDS database, Timestream database, and a DynamoDB table.
```suggestion
In this challenge, you have learned how to use Pulumi AI to generate a Pulumi program. The example we shared provisions a Kinesis Data Stream, RDS database, Timestream database, and a DynamoDB table.
```

2023-04-21 05:08 UTC, aaronkao commented
The previous name of the challenge was different. Should I go back and change all the image names and file names to be `gpt-iac` instead of `ai-architecture`? @scottslowe

2023-04-21 16:04 UTC, scottslowe commented
> The previous name of the challenge was different. Should I go back and change all the image names and file names to be `gpt-iac` instead of `ai-architecture`? @scottslowe

You can, but I don't think it's necessary.

2023-04-21 16:11 UTC, scottslowe approved these changes
Looks good!

2023-04-21 17:42 UTC, merged