SEO fixes for duplicate title tags and meta descriptions
pulumi/pulumi-hugo pull request #2725
Opened 2023-04-20 00:47 UTC by tofuni

This PR addresses duplicate title tags and meta descriptions which are part of the following issues:

- https://github.com/pulumi/registry/issues/2285
- https://github.com/pulumi/registry/issues/2286

2023-04-20 14:56 UTC, susanev commented
thank you @tofuni!! this looks good to me, but want to run locally so gonna hold this for a bit until i have time to do that.

2023-04-25 15:18 UTC, SaraDPH requested changes
I changed the Pulumi Challenge meta description

2023-04-25 15:18 UTC, SaraDPH commented on themes/default/content/blog/pulumi-challenge-september/index.md
> +meta_desc: The Pulumi Challenge continues! Take this month’s challenge and win another unique piece of swag!
```suggestion
meta_desc: Take the Pulumi Challenge - use a template to build a serverless application with AWS API Gateway and Lambda in less than 5 mins.
```

2023-04-25 15:21 UTC, SaraDPH approved these changes

2023-04-25 15:57 UTC, tofuni commented
Awesome - thank you @susanev and @SaraDPH!!

2023-04-25 22:48 UTC, susanev approved these changes

2023-04-25 22:48 UTC, merged