Add data disclaimer for pulumi ai
pulumi/pulumi-hugo pull request #2755
Opened 2023-04-26 21:26 UTC by zchase

## Description

This PR adds a disclaimer on the Pulumi AI project that data may be used to improve the results of Pulumi AI in the future

Fixes: https://github.com/pulumi/pulumi-hugo/issues/2751

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.

2023-04-26 22:17 UTC, AaronFriel approved these changes
@susanev this looks good to me, can you take a look?

2023-04-27 01:14 UTC, cnunciato requested changes
Text is fine, but I'd love to take a crack at making this a little less visually dominating. Mind if I do that?

2023-04-27 01:20 UTC, susanev approved these changes

2023-04-27 01:20 UTC, susanev commented on themes/default/content/ai/_index.md
> +The prompts you submit and the results may be used by Pulumi to improve the results of Pulumi AI in the future.
```suggestion
Submitted prompts and results may be used by Pulumi to improve Pulumi AI.
```

2023-04-27 01:23 UTC, susanev commented
@cnunciato want to do a follow up pr instead? @anita-trimbur has new note styles we should use.

2023-06-22 22:35 UTC, cnunciato commented
@zchase Let me know what you think -- I just tightened the words up a bit and removed the styling to keep the note from competing with the content above and below it.

2023-06-22 22:35 UTC, cnunciato approved these changes

2023-06-23 14:32 UTC, zchase commented
@cnunciato Looks great!! Thank you!

2023-06-23 14:32 UTC, merged