Add Skai migration post
pulumi/pulumi-hugo pull request #2823
Opened 2023-05-13 20:51 UTC by cnunciato

## Description

Add guest post from Danny Zalkind.

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

2023-05-14 11:19 UTC, dannyz1983 approved these changes

2023-05-15 00:45 UTC, scottslowe requested changes
With the exception of the spelling error in the opening paragraph, consider the rest of these as suggestions.

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +> Danny Zalkind is the DevOps group manager for Skai, an award-winning intelligent marketing platform. He brings his 15 years of exprience of managing tech teams to his current role where he's dedica
```suggestion
> Danny Zalkind is the DevOps group manager for Skai, an award-winning intelligent marketing platform. He brings his 15 years of experience of managing tech teams to his current role where he's dedicated to allow Skai R&D to efficiently produce and serve software. You can find him on [Linkedin](https://www.linkedin.com/in/danny-zalkind-01602b56/).
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +## Offloading a piece of pie to AWS
```suggestion
## Offloading a piece of the pie to AWS
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +When looking for a solution, we were looking for a service that will mark the following checkboxes:
```suggestion
When looking for a solution, we were looking for a service that would mark the following checkboxes:
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +* Fully automatable using our main Infrastructure as Code framework Pulumi.
```suggestion
* Fully automatable using Pulumi, our main Infrastructure as Code framework.
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +Finally, to make sure that the data is valid and we have no data discrepancies on the Keyspaces side, we've added a Lambda function to periodically sample the data and compare it to the data in our o
```suggestion
Finally, to make sure that the data is valid and we have no data discrepancies on the Keyspaces side, we added a Lambda function to periodically sample the data and compare it to the data in our on-prem cluster.
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +## Lets start provisioning
```suggestion
## Let's start provisioning
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +Keyspaces requires creating a logical entity called a keyspace, which groups related tables relevant for one or more applications. After that, we will iterate over our config and create each table wi
```suggestion
Keyspaces requires creating a logical entity called a keyspace, which groups related tables relevant for one or more applications. After that, we iterate over our config and create each table with the relevant columns and the preferred provisioning mode --- either "on-demand" or "provisioned," depending on our workload pattern. A provisioned workload in pre-allocated and thus significantly (x7) lower in hourly price, suitable mainly for use cases where the workload is quite predictable with no spikes.
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +Finally we will populate AWS tags in order to be able track costs and performance metrics.
```suggestion
Finally we populate AWS tags in order to be able track costs and performance metrics.

The following Python code illustrates the process:
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +Next we will define and create a Lambda function that samples and compares data between the data newly ingested into  Keyspaces, our on-premise Cassandra cluster, and our data lake Snowflake.
```suggestion
Next we define and create a Lambda function that samples and compares data between the data newly ingested into  Keyspaces, our on-premise Cassandra cluster, and our data lake Snowflake.
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +We created an abstract class implementation of AWS Lambda to standardize our various Lambda implementations and keep the code readable. This class returns all needed arguments, configuration, layers,
```suggestion
We created an abstract class implementation of AWS Lambda to standardize our various Lambda implementations and keep the code readable. This class returns all needed arguments, configuration, layers, etc. Here is some Python code that shows our abstraction, named `AwsFunction`:
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +Now we will instantiate the abstract class as part of our "building block" component class, create the function, triggers and invocation:
```suggestion
Now we instantiate the abstract class as part of our "building block" component class, create the function, triggers and invocation:
```

2023-05-15 00:45 UTC, scottslowe commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +Note: This only a partial code example, meant to demonstrate the way we use object-oriented paradigms to create reusable building-blocks of code to be consumed by various platform and R&D teams to pr
Should we consider using `{{% notes %}}` to set this off?

2023-05-16 22:50 UTC, cnunciato reviewed
Fix date, add tag.

2023-05-16 22:50 UTC, cnunciato commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +date: 2023-05-15
```suggestion
date: 2023-05-16
```

2023-05-16 22:50 UTC, cnunciato commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +> Danny Zalkind is the DevOps group manager for Skai, an award-winning intelligent marketing platform. He brings his 15 years of experience of managing tech teams to his current role where he's dedic
```suggestion
> Danny Zalkind is the Senior Director of Infrastructure Engineering for Skai, an award-winning intelligent marketing platform. He brings his 15 years of experience of managing tech teams to his current role where he's dedicated to allow Skai R&D to efficiently produce and serve software. You can find him on [Linkedin](https://www.linkedin.com/in/danny-zalkind-01602b56/).
```

2023-05-16 22:50 UTC, cnunciato commented on themes/default/content/blog/how-skai-migrated-to-aws-keyspaces-with-pulumi/index.md
> +    - migration
```suggestion
    - migration
    - guest-post
```

2023-05-17 00:50 UTC, merged