Add PulumiUP demo videos to pages
pulumi/pulumi-hugo pull request #3119
Opened 2023-06-29 00:20 UTC by gthuang

## Description
Adding demo videos of Review Stacks, Property Search, TF conversion, and Azure Native to blogs, docs, and webpages.

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2023-06-29 13:02 UTC, mnlumi requested changes
Adding these to the top of the blog posts is not a great look on the preview page ([Ref: Avoid using images or code samples in the first 70 words](https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/archetypes/blog-post/index.md?plain=1#L50-L52)). Also, it seems kind of odd to drop a video as the first line of the blog post without any context or lead-in.

![Screenshot 2023-06-29 at 8 53 00 AM](https://github.com/pulumi/pulumi-hugo/assets/118926824/2ab08500-a2c6-4e9a-b4bb-761bb3d70878)
![Screenshot 2023-06-29 at 8 53 19 AM](https://github.com/pulumi/pulumi-hugo/assets/118926824/c752663d-2762-42ff-9a4d-9c2c9d6e83c6)
![Screenshot 2023-06-29 at 8 53 08 AM](https://github.com/pulumi/pulumi-hugo/assets/118926824/83d1ad28-2067-4b12-be84-f2fe4aa5caca)

2023-06-29 16:51 UTC, gthuang commented
> Adding these to the top of the blog posts is not a great look on the preview page ([Ref: Avoid using images or code samples in the first 70 words](https://github.com/pulumi/pulumi-hugo/blob/master/themes/default/archetypes/blog-post/index.md?plain=1#L50-L52)). Also, it seems kind of odd to drop a video as the first line of the blog post without any context or lead-in.
> 
> ![Screenshot 2023-06-29 at 8 53 00 AM](https://user-images.githubusercontent.com/118926824/249778238-2ab08500-a2c6-4e9a-b4bb-761bb3d70878.png) ![Screenshot 2023-06-29 at 8 53 19 AM](https://user-images.githubusercontent.com/118926824/249778239-c752663d-2762-42ff-9a4d-9c2c9d6e83c6.png) ![Screenshot 2023-06-29 at 8 53 08 AM](https://user-images.githubusercontent.com/118926824/249778241-83d1ad28-2067-4b12-be84-f2fe4aa5caca.png)

i made these changes

2023-06-30 13:23 UTC, mnlumi reviewed
The videos need to be moved out of the beginning of all blog posts.

2023-06-30 13:23 UTC, mnlumi commented on themes/default/content/docs/pulumi-cloud/deployments/review-stacks.md
> +
This needs to be moved.

2023-06-30 13:23 UTC, mnlumi commented on themes/default/content/blog/review-stacks/index.md
> +
This needs to be moved.

2023-06-30 13:28 UTC, mnlumi approved these changes

2023-06-30 17:04 UTC, merged