fix: missing fmt in the go program and improve the "Pulumi Fundamentals" tutorial
pulumi/pulumi-hugo pull request #3244
Opened 2023-08-09 08:31 UTC by scraly

## Description

I fixed a missing "fmt" import in the go program, without i the tutorial is not working.
I have also improved the tutorial with more information to guide the user.

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] I have manually confirmed that all new links work.

2023-10-25 21:56 UTC, scottslowe requested changes
One very minor suggested change; otherwise, looks good and thank you very much for your contribution!

2023-10-25 21:56 UTC, scottslowe commented on themes/default/content/learn/pulumi-fundamentals/create-docker-images/index.md
> +Add this code at the bottom of your program, just before the last return nil statement:
```suggestion
Add this code at the bottom of your program, just before the last `return nil` statement:
```

2023-10-26 06:02 UTC, scraly commented
Updated 🙂

2023-10-26 15:39 UTC, scottslowe approved these changes
Approved, thanks again for the contribution!

2023-10-26 15:55 UTC, merged