MS Teams blog post
pulumi/pulumi-hugo pull request #3316
Opened 2023-08-28 19:07 UTC by meagancojocar

## Description

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2023-08-28 20:00 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +      format: slack
```suggestion
      displayName: my-teams-channel
      organizationName: my-org
      payloadUrl: "https://xxxxx.webhook.office.com/xxxxxxxxx"
      format: ms_teams
```

2023-08-28 20:00 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +      format: slack
```suggestion
      displayName: my-teams-channel
      organizationName: my-org
      projectName: webhook-examples
      stackName: dev
      payloadUrl: "https://xxxxx.webhook.office.com/xxxxxxxxx"
      format: ms_teams
```

2023-08-28 20:01 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +    format=pulumiservice.WebhookFormat.SLACK,
```suggestion
    display_name="my-teams-channel",
    organization_name="my-org",
    payload_url="https://xxxxx.webhook.office.com/xxxxxxxxx",
    format=pulumiservice.WebhookFormat.MICROSOFT_TEAMS,
```

2023-08-28 20:02 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +    format=pulumiservice.WebhookFormat.SLACK)
```suggestion
    display_name="my-teams-channel",
    organization_name="my-org",
    project_name="webhook-examples",
    stack_name="dev",
    payload_url="https://xxxxx.webhook.office.com/xxxxxxxxx",
    format=pulumiservice.WebhookFormat.MICROSOFT_TEAMS)
```

2023-08-28 20:04 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +			Format:           pulumiservice.WebhookFormatSlack,
```suggestion
			DisplayName:      pulumi.String("my-teams-channel"),
			OrganizationName: pulumi.String("my-org"),
			PayloadUrl:       pulumi.String("https://xxxxx.webhook.office.com/xxxxxxxxx"),
			Format:           pulumiservice.WebhookFormatMicrosoftTeams,
```

2023-08-28 20:04 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +			Format:           pulumiservice.WebhookFormatSlack,
```suggestion
			DisplayName:      pulumi.String("my-teams-channel"),
			OrganizationName: pulumi.String("my-org"),
			ProjectName:      pulumi.String("webhook-examples"),
			StackName:        pulumi.String("dev"),
			PayloadUrl:       pulumi.String("https://xxxxx.webhook.office.com/xxxxxxxxx"),
			Format:           pulumiservice.WebhookFormatMicrosoftTeams,
```

2023-08-28 20:05 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +        Format = PulumiService.WebhookFormat.Slack,
```suggestion
        DisplayName = "my-teams-channel",
        OrganizationName = "my-org",
        PayloadUrl = "https://xxxxx.webhook.office.com/xxxxxxxxx",
        Format = PulumiService.WebhookFormat.MicrosoftTeams,
```

2023-08-28 20:05 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +        Format = PulumiService.WebhookFormat.Slack,
```suggestion
        DisplayName = "my-teams-channel",
        OrganizationName = "my-org",
        ProjectName = "webhook-examples",
        StackName = "dev",
        PayloadUrl = "https://xxxxx.webhook.office.com/xxxxxxxxx",
        Format = PulumiService.WebhookFormat.MicrosoftTeams,
```

2023-08-28 20:06 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +            .format("slack")
```suggestion
            .displayName("my-teams-channel")
            .organizationName("my-org")
            .payloadUrl("https://xxxxx.webhook.office.com/xxxxxxxxx")
            .format("ms_teams")
```

2023-08-28 20:06 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +            .format("slack")
```suggestion
            .displayName("my-teams-channel")
            .organizationName("my-org")
            .projectName("webhook-examples")
            .stackName("dev")
            .payloadUrl("https://xxxxx.webhook.office.com/xxxxxxxxx")
            .format("ms_teams")
```

2023-08-28 20:11 UTC, komalali commented on themes/default/content/blog/ms-teams-integration/index.md
> +The Pulumi Service provider allows you to create Pulumi Cloud resources via Pulumi. You can provision and manage webhooks, including Slack-formatted webhooks, using this provider.
```suggestion
The Pulumi Service provider allows you to create Pulumi Cloud resources via Pulumi. You can provision and manage webhooks, including Microsoft Teams webhooks, using this provider.
```

2023-08-29 15:59 UTC, scottslowe requested changes
A few typos to be corrected and a suggestion for a link, but otherwise it looks good. I assume the GIF referenced in the text hasn't yet been uploaded, as it wasn't showing in the preview URL?

2023-08-29 15:59 UTC, scottslowe commented on themes/default/content/blog/ms-teams-integration/index.md
> +Before today Pulumi customers used Pulumi Cloud Webhooks to set up generic JSON webhooks. When events occur, we send a HTTP POST request to any registered listeners. Webhooks can then be used to send
```suggestion
Before today, Pulumi customers used Pulumi Cloud Webhooks to set up generic JSON webhooks. When events occur, we send a HTTP POST request to any registered listeners. Webhooks can then be used to send notifications to an app (like Microsoft Teams), start running automated tests, or even to update another stack! We have now built support for Microsoft Teams formatted webhooks, which allow you to quickly enable notifications about your Pulumi stacks and organizations into your Microsoft Teams workspace by simply providing a [incoming webhook URL](https://learn.microsoft.com/en-us/microsoftteams/platform/webhooks-and-connectors/how-to/add-incoming-webhook).
```

2023-08-29 15:59 UTC, scottslowe commented on themes/default/content/blog/ms-teams-integration/index.md
> +Before today Pulumi customers used Pulumi Cloud Webhooks to set up generic JSON webhooks. When events occur, we send a HTTP POST request to any registered listeners. Webhooks can then be used to send
Don't we have a blog post that talks about using webhooks to update another stack? It might be worth adding a link here if so.

2023-09-11 18:15 UTC, komalali approved these changes

2023-09-11 18:22 UTC, scottslowe approved these changes

2023-09-11 18:22 UTC, merged