Add deletedWith documentation
pulumi/pulumi-hugo pull request #3401
Opened 2023-09-23 01:35 UTC by cleverguy25

## Description

Add docs per https://github.com/pulumi/pulumi-hugo/issues/2401

## Checklist:

- [X] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2023-09-23 02:00 UTC, ericrudder commented on themes/default/content/docs/concepts/options/_index.md
> +- [deletedWith](/docs/concepts/options/deletedwith/): If set, the providers Delete method will not be called for this resource if the specified resource is being deleted as well.
```suggestion
- [deletedWith](/docs/concepts/options/deletedwith/): If set, the provider's Delete method will not be called for this resource if the specified resource is being deleted as well.
```

2023-09-23 02:01 UTC, ericrudder commented on themes/default/content/docs/concepts/options/deletedwith.md
> +Pulumi will normally call the providers delete action for every resource during a delete operation. Sometimes this is redundant if another resource is deleted, such as a parent container resource, an
```suggestion
Pulumi will normally call the provider's delete action for every resource during a delete operation. Sometimes, this is redundant if another resource is also deleted, such as a parent container resource, and can cause your delete or destroy operations to take longer than needed.
```

2023-09-23 04:28 UTC, cleverguy25 commented on themes/default/content/docs/concepts/options/_index.md
> +- [deletedWith](/docs/concepts/options/deletedwith/): If set, the providers Delete method will not be called for this resource if the specified resource is being deleted as well.
Done

2023-09-23 04:28 UTC, cleverguy25 commented on themes/default/content/docs/concepts/options/deletedwith.md
> +Pulumi will normally call the providers delete action for every resource during a delete operation. Sometimes this is redundant if another resource is deleted, such as a parent container resource, an
Done

2023-09-25 12:17 UTC, ringods requested changes

2023-09-25 15:46 UTC, cleverguy25 commented on themes/default/content/docs/concepts/options/deletedwith.md
> +      deletedWtih: ${ns}
Fixed

2023-09-25 15:46 UTC, cleverguy25 commented on themes/default/content/docs/concepts/options/deletedwith.md
> +dep = k8s.apps.v1.Deployment("res2", opts=ResourceOptions(deletedWith=ns))
Fixed

2023-09-25 15:46 UTC, cleverguy25 commented on themes/default/content/docs/concepts/options/deletedwith.md
> +    new CustomResourceOptions { DeletedWith = { ns } });
Fixed

2023-09-25 15:49 UTC, ringods approved these changes

2023-09-25 15:54 UTC, merged