state convert blog
pulumi/pulumi-hugo pull request #3428
Opened 2023-09-30 21:12 UTC by Frassle

## Description

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2023-10-02 13:46 UTC, jaxxstorm commented on themes/default/content/blog/converting-full-terraform-states-to-pulumi/index.md
> +date: 2023-06-12
Incorrect date?

2023-10-02 13:50 UTC, jaxxstorm approved these changes

2023-10-02 13:50 UTC, jaxxstorm commented on themes/default/content/blog/converting-full-terraform-states-to-pulumi/index.md
> +Building on our work of [converting Terraform projects](/docs/converting-full-terraform-programs-to-pulumi), we now have support for converting Terraform state.
```suggestion
Building on our work of [converting Terraform projects](/docs/converting-full-terraform-programs-to-pulumi), we now have support for adopting resources from Terraform state
```

2023-10-03 04:40 UTC, scottslowe requested changes

2023-10-03 04:40 UTC, scottslowe commented on themes/default/content/blog/converting-full-terraform-states-to-pulumi/index.md
> +From [v3.87.0](/docs/install) we have extended our converter system to state not just code. So now it's possible to import resources from other state system, the first of which we have support for be
```suggestion
From [v3.87.0](/docs/install) we have extended our converter system to also include state in addition to code. So now it's possible to import resources from other state systems, the first of which is Terraform.
```

2023-10-05 12:10 UTC, Frassle commented on themes/default/content/blog/converting-full-terraform-states-to-pulumi/index.md
> +date: 2023-06-12
Yeh copy paste

2023-10-05 13:08 UTC, Frassle commented
Need to update the meta.png for this

2023-10-24 03:37 UTC, scottslowe approved these changes
One small suggested change (the wording seems awkward), but no need to block on it.

2023-10-24 03:37 UTC, scottslowe commented on themes/default/content/blog/converting-full-terraform-states-to-pulumi/index.md
> +In the prior blog post about converting from Terraform we called out that while it was great that the converter could migrate a Terraform project, but what if you had existing infrastructure resource
```suggestion
In the prior blog post about converting from Terraform we called out that it was great that the converter could migrate a Terraform project, but it didn't address situations where you had existing infrastructure resources.
```

2023-10-25 19:35 UTC, merged