Update blog with post detailing events of the outage on October 6
pulumi/pulumi-hugo pull request #3508
Opened 2023-10-16 19:29 UTC by caseyyh

## Description

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2023-10-17 17:36 UTC, scottslowe requested changes

2023-10-17 17:36 UTC, scottslowe commented on themes/default/content/blog/post-mortem-2023-10-06/index.md
> +Last Friday, Pulumi suffered a 24 minute outage during which we failed to process 74.7% of received requests.
```suggestion
At Pulumi, we understand that Pulumi Cloud plays an important role in how our customers address their infrastructure management challenges. As a result, we strive for the highest levels of availability and performance in Pulumi Cloud. Unfortunately, on Friday, October 6, 2023, Pulumi Cloud suffered a 24 minute outage during which we failed to process 74.7% of received requests. In this post, we'd like to share our findings on the root cause of this outage, and the steps we are taking to ensure this sort of outage doesn't happen again.
```

2023-10-17 17:36 UTC, scottslowe commented on themes/default/content/blog/post-mortem-2023-10-06/index.md
> +Last Friday, Pulumi suffered a 24 minute outage during which we failed to process 74.7% of received requests.
Just one potential way to rewrite the opening. Right now it feels very abrupt.

2023-10-18 02:27 UTC, joeduffy commented on themes/default/content/blog/post-mortem-2023-10-06/index.md
> +    - post-mortem
Total nitpick:

```suggestion
    - postmortem
```

2023-10-18 02:27 UTC, joeduffy commented on themes/default/content/blog/post-mortem-2023-10-06/index.md
> +    - outage
```suggestion
```

2023-10-18 17:11 UTC, scottslowe approved these changes

2023-10-18 20:28 UTC, merged