Add ai apps workshop
pulumi/pulumi-hugo pull request #3657
Opened 2023-11-21 20:29 UTC by sean1588

## Description

DO NOT MERGE: I still need to get the hubspot form id before we can ship this.

Add AI apps workshop. 

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2023-11-21 21:16 UTC, shughes26 approved these changes

2023-11-21 23:55 UTC, aaronkao requested changes
Updated the abstract with some comments from Pinecone

2023-11-21 23:55 UTC, aaronkao commented on themes/default/content/resources/ai-apps-to-production/index.md
> +        This workshop is designed to help AI developers and engineers build and scale AI infrastructure. We will guide you through the Pulumi platform with diagrams and a series of labs to help accel
```suggestion
        This workshop is designed to help AI developers and engineers gain valuable insights and practical strategies for evolving AI applications into resilient and efficient cloud-native solutions. We will guide you through the Pulumi platform with diagrams and a series of labs to help accelerate your AI apps.
```

2023-11-21 23:55 UTC, aaronkao commented on themes/default/content/resources/ai-apps-to-production/index.md
> +        What does it take to go from an idea in a notebook to an application handling real-world traffic? In this workshop, the Pinecone and Pulumi teams will explore the infrastructure and service a
```suggestion
        What does it take to go from an idea in a notebook to an application handling real-world traffic? In this workshop, the Pinecone and Pulumi teams will explore the infrastructure and service architecture you need to scale AI apps in production. We will delve into deploying high-volume AI systems through scalable microservices, efficient data processing, and seamless synchronization between user interfaces and databases. We will examine the nuances of containerization for enhanced portability and Infrastructure as Code (IaC) for streamlined cloud deployments. The workshop will also discuss industry best practices in scalability and security for production-grade AI systems in a cloud-native landscape.
```

2023-11-21 23:55 UTC, aaronkao commented on themes/default/content/resources/ai-apps-to-production/index.md
> +        - How to provision, update, and destroy AWS resources
```suggestion
        - How to provision, update, and destroy AWS resources (Amazon ECS clusters, networking infrastructure, messaging queues, and Amazon RDS Postgres databases)
```

2023-11-22 17:14 UTC, isaac-pulumi approved these changes

2023-11-22 17:25 UTC, merged