[project-file] add newly supported template fields
pulumi/pulumi-hugo pull request #3713
Opened 2023-12-07 00:06 UTC by dschaller

## Description
Template blocks now support optional `displayName` and `metadata` fields that are used by the console to aid in the discovery of any template (pulumi-hosted or self-hosted).

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).

2023-12-07 00:11 UTC, lukehoban approved these changes
🙌

2023-12-07 00:11 UTC, lukehoban commented on themes/default/content/docs/concepts/projects/project-file.md
> +| `displayName` | optional | A user-friendly name for the template. |
Minor - but should we make any suggestion on format?  I think we generally are encouraging Title Case and relatively short?

2023-12-15 18:32 UTC, cnunciato requested changes
Ok to close this PR, assuming we aren't currently planning to do this?

2023-12-16 21:39 UTC, dschaller commented
I feel like we might still want to add this but should maybe denote that it requires version>=3.95

2023-12-22 20:06 UTC, dschaller commented
@cnunciato updated - let me know what you think

2024-01-03 21:52 UTC, cnunciato approved these changes

2024-01-04 00:30 UTC, merged