Tutorial: Unit testing stack references in go
pulumi/pulumi-hugo pull request #3795
Opened 2023-12-28 20:30 UTC by desteves

## Description

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2024-01-04 22:46 UTC, scottslowe requested changes
Overall, this is good. I got a bit lost in the middle of the process, so depending on the intended target audience, this tutorial might benefit from some slight additional context/information around each step and what it's doing.

2024-01-04 22:46 UTC, scottslowe commented on themes/default/content/docs/using-pulumi/testing/unit-sr.md
> +[**Learn more about Stack References**](/docs/using-pulumi/testing/unit).
I think this link may be incorrect...?

2024-01-08 15:29 UTC, desteves commented on themes/default/content/docs/using-pulumi/testing/unit-sr.md
> +You can write unit tests and assertions using your favorite frameworks and libraries. We use Ginkgo and Gomega.
Done

2024-01-09 22:18 UTC, desteves commented
> Overall, this is good. I got a bit lost in the middle of the process, so depending on the intended target audience, this tutorial might benefit from some slight additional context/information around each step and what it's doing.

Thanks for the feedback, Scott; I'll add info bubbles and more details for the concepts that fall more on the advanced end.

2024-05-29 20:57 UTC, closed without merging