draft developer workflow blog
pulumi/pulumi-hugo pull request #3815
Opened 2024-01-08 21:00 UTC by usrbinkat

## Description

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2024-01-22 16:49 UTC, desteves commented on themes/default/content/blog/pulumi-developer-workflow/index.md
> +<!--more-->
It might be beneficial to add a ToC somewhere around here.

2024-01-22 16:50 UTC, desteves commented on themes/default/content/blog/pulumi-developer-workflow/index.md
> +> #### What's in a Day 0?
Add "DevOps" so it reads DevOps Day 0

2024-01-22 18:47 UTC, usrbinkat commented
@desteves some of the new line delimiters (double trailing white spaces) keep getting stripped by vscode :/

These should be bullets.

![image](https://github.com/pulumi/pulumi-hugo/assets/54747391/24bb479d-e09d-4c55-8a15-3e2291884cd6)

2024-01-22 22:05 UTC, scottslowe requested changes
Solid, but a few suggested changes/corrections/additions that need to be made. I'd also suggest adding a call to action (CTA), or moving the Conclusion section to the very end (after Cleanup) and embedding a CTA there.

2024-01-22 22:05 UTC, scottslowe commented on themes/default/content/blog/pulumi-developer-workflow/index.md
> +Let's try it!
```suggestion
Let's try it! (Reminder: Perform all these steps from within the Codespaces IDE.)
```

2024-01-22 22:05 UTC, scottslowe commented on themes/default/content/blog/pulumi-developer-workflow/index.md
> +> **Follow the link for the full playlist of 2023 Pulumi Up sessions**
Reminder to make sure we add the hyperlink here

2024-01-22 22:05 UTC, scottslowe commented on themes/default/content/blog/pulumi-developer-workflow/index.md
> +#### Conclusion
Seems to me like we should pull the Conclusion section out of the details and show it all the time (not only when Details is expanded).

2024-01-23 04:16 UTC, usrbinkat commented on themes/default/content/blog/pulumi-developer-workflow/index.md
> +### Three tips to learn new technology:
ha! yeah.

2024-01-23 23:04 UTC, scottslowe approved these changes

2024-01-23 23:06 UTC, merged