ESC Content Enhancements
pulumi/pulumi-hugo pull request #3828
Opened 2024-01-10 15:52 UTC by toriancrane

## Description

This PR does the following:

- Moves existing ESC content from under Pulumi Cloud to standalone top level
- Removes Get Started one page tutorial
- Adds the following pages:
  - Get started hub page
  - Before you begin
  - Create environment
  - Store and retrieve secrets

2024-01-16 22:49 UTC, scottslowe requested changes
Generally looks great, but I found one file that appears to be orphaned (the page on importing environments). I wasn't sure if that was intentional, or accidental.

2024-01-16 22:49 UTC, scottslowe commented on themes/default/content/docs/esc/get-started/import-environments.md
Is this file supposed to show up somewhere? I don't see it in the menu, and I can't seem to access it via URL, either.

2024-01-17 11:42 UTC, toriancrane commented on themes/default/content/docs/esc/get-started/import-environments.md
I think this had something to do with the merge conflict. It should be showing up now.

2024-01-17 16:59 UTC, scottslowe approved these changes

2024-01-17 18:05 UTC, cnunciato commented on themes/default/content/docs/esc/_index.md
> +no_on_this_page: true
Removing this line will get the right-hand nav to show up:

```suggestion
```

2024-01-18 16:22 UTC, merged