Clarity on declarative and imperative approaches with Pulumi
pulumi/pulumi-hugo pull request #3862
Opened 2024-01-21 21:27 UTC by interurban

Adding a section on our how Pulumi works to describe Pulumi's powerful declarative model and how this relates to using imperative languages to author y our solutions.

## Description

## Checklist:

- [ ] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [ ] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [ ] I have manually confirmed that all new links work.
- [ ] I added aliases (i.e., redirects) for all filename changes.
- [ ] If making css changes, I rebuilt the bundle.

2024-01-21 21:28 UTC, interurban commented
Hey @ringods I've made some adjustments to your blog title to help with SEO and would appreciate your thoughts on how i've incorporated things into the docs. thanks!

2024-01-22 14:25 UTC, ringods approved these changes

2024-01-22 14:25 UTC, ringods commented on themes/default/content/docs/concepts/how-pulumi-works.md
> +## Language hosts
The second word is made lowercase here, but not in other titles further down like `Resource Providers`. Is this an inconsistency now, or is there still a reason behind it? I'm not an native English speaker, so I might not know.

2024-01-22 14:25 UTC, ringods commented on themes/default/content/docs/concepts/how-pulumi-works.md
> +Like the language runtime itself, the SDKs are available as regular packages. For example, there is a [`@pulumi/aws`](https://www.npmjs.com/package/@pulumi/aws) package for Node available on npm and
> ... download the resource plugin from Pulumi.com or partners.

We do not maintain all the SDKs or plugin binaries.

2024-01-22 19:18 UTC, scottslowe requested changes

2024-01-22 22:13 UTC, scottslowe approved these changes

2024-01-22 23:16 UTC, merged

2024-01-23 00:55 UTC, cnunciato reviewed
Sorry for not getting this in sooner? It merged while I was still in the middle of my review. Feel free to use what you like. Thanks!

2024-01-23 00:55 UTC, cnunciato commented on themes/default/content/blog/pulumi-is-imperative-declarative-imperative/index.md
> +title: "Pulumi's Declarative and Imperative Approach IaC"
> Pulumi's Declarative and Imperative Approach to IaC"

Missing a "to".

We can also add `allow_long_title: true` to get past the 60-character link check if we need to.

2024-01-23 00:55 UTC, cnunciato commented on themes/default/content/docs/concepts/how-pulumi-works.md
> +With Pulumi, you author your infrastructure in your preferred programming language. When you run `pulumi up`, the Pulumi CLI starts both language host for your selected programming language as well a
This is all correct, but it feels a bit like much of what's here repeats what's already been mentioned above and also leaves out "the meat" of what this is presumably about, namely explaining "how Pulumi is declarative" -- assuming that's what we were aiming for. If we want to keep from duplicating content, would it make sense to quote, say, a portion of Ringo's post here, and link to the rest? Or pull more of the content in and rework it somehow?