Enhanced YAML Editor blog
pulumi/pulumi-hugo pull request #3963
Opened 2024-02-21 19:36 UTC by arunkumar611

Need to record the video and add it.

2024-02-21 22:23 UTC, pgavlin requested changes
would prefer we not call this the "ESC Enhanced Editor", esp. because we will continue to make improvements here, and will probably want to blog about them each time.

also suggested a few edits to decrease wordiness.

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +With [Pulumi ESC](/product/esc), our goal is to not only create a tool that simplifies the development process but also one that developers love. Building on this goal, we're excited to unveil the ne
```suggestion
With [Pulumi ESC](/product/esc), our goal is to not only create a tool that simplifies the development process but also one that developers love. In pursuit of this goal, we're excited to announce enhancements to the ESC environment editor. These enhancements are focused on addressing common challenges encountered when authoring environments: syntax errors, type errors, frequent context switches to and from documentation, and more. Our aim is to make the process of authoring environments as straightforward as possible by removing common hurdles.
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +## Highlights of the Enhanced Editor
```suggestion
## Highlights
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +- **Auto-complete**: This feature provides suggestions for code snippets and resource properties, eliminating the constant need to reference documentation. It's engineered to accelerate and refine th
```suggestion
- **Auto-complete**: This feature provides suggestions for code snippets and resource properties, easing the need to reference documentation. It is engineered to accelerate and refine the coding process, enabling developers to concentrate on innovation and problem-solving.
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +- **Enhanced Diagnostics**: This goes beyond basic syntax checks by providing in-depth insights into potential errors, coupled with real-time fix recommendations. It serves as your personal coding as
```suggestion
- **Enhanced Diagnostics**: These diagnostics go beyond basic syntax checks by providing in-depth, as-you-type insights into errors.
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +- **Hover Documentation**: Simply hover over any piece of code to see a detailed tooltip with relevant insights and examples. This instant access to information reduces manual documentation lookups,
```suggestion
- **Hover Documentation**: Hover over any piece of code to see a detailed tooltip with relevant documentation and examples. This instant access to information reduces the need to context switch, streamlining the development process and minimizing disruptions.
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +Tap 'Ctrl+Space' on the Editor reveal the list of functions and properties.
```suggestion
Tap 'Ctrl+Space' in the editor reveal the list of functions and properties. 
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +{{< video title="Pulumi ESC Enhanced Editor Demo" src="./esc-enhanced-editor-demo.mp4" autoplay="true" loop="true" >}}
```suggestion
{{< video title="Pulumi ESC editor enhancements demo" src="./esc-enhanced-editor-demo.mp4" autoplay="true" loop="true" >}}
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +We also added support for getting rich contextual information such as current user, organization, environment name to the environments. You can use it to enrich audit logs, refine OIDC subject for gr
```suggestion
We have also added support for accessing contextual information from within an ESC environment such as the current user, organization, and environment name. You can use this information to enrich audit logs, refine OIDC claims for more granular access, and more! This information is available by accessing the `context` property, and contains the following information:
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +* `context.user.login`: the user login identifier
```suggestion
* `context.user.login`: the login of the user evaluating the environment
```

2024-02-21 22:23 UTC, pgavlin commented on themes/default/content/blog/esc-enhanced-editor/index.md
> +* `context.organization.login`: the organization login identifier
```suggestion
* `context.organization.login`: the name of the user's organization
```

2024-02-22 00:08 UTC, arunkumar611 commented
@pgavlin  - Thanks for the review. I updated the title and accepted your suggestions. Let me know if you have any other suggestions.

2024-02-22 21:50 UTC, pgavlin approved these changes

2024-02-22 21:50 UTC, pgavlin requested changes
oh we also need to change that title image

2024-02-23 00:07 UTC, pgavlin approved these changes

2024-02-23 15:40 UTC, merged