Rename AWS Native Cloud Control provider
pulumi/pulumi-hugo pull request #4008
Opened 2024-03-06 15:19 UTC by danielrbradley

## Description

Ready for the GA which includes a rename, update the docs and the original launch blog post to use the new name.

Also, fix accidental reference inthe GCP docs.

Related to:
- https://github.com/pulumi/pulumi-aws-native/issues/1226

## Checklist:

- [x] I have reviewed the [style guide](https://github.com/pulumi/pulumi-hugo/blob/master/STYLE-GUIDE.md).
- [x] If blogging, I have reviewed the [blogging guide](https://github.com/pulumi/pulumi-hugo/blob/master/BLOGGING.md).
- [x] I have manually confirmed that all new links work.
- [x] I added aliases (i.e., redirects) for all filename changes.
- [x] If making css changes, I rebuilt the bundle.

2024-03-06 17:56 UTC, scottslowe requested changes
One small typo to fix

2024-03-06 17:56 UTC, scottslowe commented on themes/default/content/docs/using-pulumi/pulumi-packages/how-to-author.md
> +- The name should start with `pulumi-`, like our [`pulumi-aws-native`](/registry/packages/aws-native) AWS Cloud Control Native Provider and our [`pulumi-eks`](/registry/packages/eks) Component for AW
```suggestion
- The name should start with `pulumi-`, like our [`pulumi-aws-native`](/registry/packages/aws-native) AWS Native Cloud Control Provider and our [`pulumi-eks`](/registry/packages/eks) Component for AWS Elastic Kubernetes Service (EKS)
```

2024-03-07 22:12 UTC, scottslowe approved these changes

2024-03-28 12:19 UTC, toriancrane approved these changes
I'm guessing Scott's approval got rolled back after he left(?)

I'm approving to unblock.

2024-04-17 10:38 UTC, danielrbradley commented
Closing as this rename is not going ahead for now

2024-04-17 10:38 UTC, closed without merging