WIP: Add page for developer advocates
pulumi/pulumi-hugo pull request #448
Opened 2021-07-27 17:50 UTC by mattstratton

This adds a page at `/developer-advocates` which lists the current DAs, along with some other content.

Note: this adds an optional field to the team entries in the `data` directory; anyone with `role = "developer-advocate"` will show up on this page.

We are still working through the content, so this is a draft PR at the moment.

Signed-off-by: Matt Stratton <matt.stratton@gmail.com>

2021-07-27 18:06 UTC, susanev reviewed
a few thoughts..
- should this live under /about?
- could we use the contact us form instead of the email link?

2021-07-27 18:09 UTC, mattstratton commented
> should this live under /about?
I don't mind that; the only thing I was thinking in my head was an easy to remember URL if we need it to rattle off to people?

> should this be linked to from somewhere on the about page?
I defer to @aaronkao on this based on what his vision is for this page, but I don't mind that either :)

> could we use the contact us form instead of the email link?
I already started to talk to @zchase about how we could do the form instead; I much prefer that myself. I just tossed the email link in so the WIP wasn't so empty, but ideally a form instead of having our email address out there for spam harvesting!

2021-07-27 18:14 UTC, susanev commented
cool, @aaronkao when we are adding new pages id love for us to think about the navigation and how they fit into our current navigation structure. happy to help however i can.

2021-07-28 00:07 UTC, cnunciato approved these changes
LGTM, though defer to @aaronkao on the details.

Semi-relatedly, IIRC we've also talked about having a page at https://www.pulumi.com/community (which today still 404s -- 😢) that might be a good place to collect community resources & things; I can imaging something like this living on a page like that, too, or this page being linked _from_ that page, or something -- just figured I'd mention that as something to think about as well.

2021-07-28 00:09 UTC, mattstratton commented on themes/default/content/developer-advocates/_index.md
> +meta_desc: Pulumi is a Seattle-based company that enables teams to create, deploy, and manage modern cloud applications and infrastructure.
yah, I didn't update that yet; i'm going to loop back to that once the actual content on the page is finalized

2021-07-28 15:39 UTC, mattstratton commented
> LGTM, though defer to @aaronkao on the details.
> 
> Semi-relatedly, IIRC we've also talked about having a page at [pulumi.com/community](https://www.pulumi.com/community) (which today still 404s -- 😢) that might be a good place to collect community resources & things; I can imaging something like this living on a page like that, too, or this page being linked _from_ that page, or something -- just figured I'd mention that as something to think about as well.

Talking to Aaron, we think that having it under `/community` makes a lot of sense. I can update the PR for that.

What do we think about adding an alias in hugo so that `/developer-advocates` works as well as `/community/developer-advocates`? Just for ease of sharing the link.

Unrelated, I really would love if we had a pulumi branded shortlink thing, like `pulu.mi/devadvocates`

(note: `.mi` is not a valid TLD lol)

2021-07-28 15:59 UTC, mattstratton commented
OK the latest commit moves the "real" URL of the page to `/community/developer-advocates` but also has `/developer-advocates` redirect to it as well:

http://pulumi-hugo-origin-pr-448-c340738f.s3-website.us-west-2.amazonaws.com/community/developer-advocates

http://pulumi-hugo-origin-pr-448-c340738f.s3-website.us-west-2.amazonaws.com/developer-advocates

We will want to put something inside `/community` at some point too of course, right now [it just makes a relatively empty page](http://pulumi-hugo-origin-pr-448-c340738f.s3-website.us-west-2.amazonaws.com/community/).

2021-07-28 16:30 UTC, cnunciato commented
> What do we think about adding an alias in hugo so that /developer-advocates works as well as /community/developer-advocates? Just for ease of sharing the link.

Totally reasonable, alias away. 😄

2021-08-10 15:07 UTC, nimbinatus requested changes
Some suggestions on wording

2021-08-10 15:07 UTC, nimbinatus commented on themes/default/layouts/page/developer-advocates.html
> +            and their social media contact info! We would love to help you be super cool and rad!
Suggestion to match the current messaging a bit more, and narrowing the focus a bit so people aren't encouraged to reach out for not-advocate reasons.

```suggestion
            The Pulumi Developer Advocate team wants to help you build, manage, and deploy
            all the things and learn something new along the way. Here's a list of the team
            and their social media. Need help? We would love to help you accomplish your goals!
```

2021-08-10 17:03 UTC, mattstratton commented
Ugh! how did I mess this up. I rebased but I guess I should have done a merge commit; those files shouldn't show as changed. Ugh.

2021-08-10 17:32 UTC, mattstratton commented
Since my attempts at rebasing just made things a huge mess, I'll try a new PR. Sorry!

2021-08-10 17:32 UTC, closed without merging