Added text if you need access to service
pulumi/pulumi-hugo pull request #993
Opened 2022-01-21 16:38 UTC by pierskarsenbarg

For example, if you don't have external internet access

2022-01-21 17:39 UTC, susanev approved these changes

2022-01-21 17:39 UTC, susanev commented on themes/default/content/docs/troubleshooting/_index.md
> +## I can't connect to the Pulumi Service
could we maybe work network into the heading?

2022-01-21 17:39 UTC, susanev commented on themes/default/content/docs/troubleshooting/_index.md
> +If your network is locked down to external traffic, you're using the service to manage your state, and your security team need to give you access to the service then here's the information you can pa
```suggestion
If your network is locked down to external traffic, you're using the service to manage your state, and your security team needs to give you access to the service then here's the information you can pass over.
```

2022-01-22 00:08 UTC, cnunciato requested changes
Thanks for adding this! Some minor suggestions but otherwise 👍.

2022-01-22 00:08 UTC, cnunciato commented on themes/default/content/docs/troubleshooting/_index.md
> +If your network is locked down to external traffic, you're using the service to manage your state, and your security team needs to give you access to the service then here's the information you can p
```suggestion
If your network blocks external traffic and you're using the Pulumi Service to manage your state, your security team may need the following details to allow the Pulumi CLI to connect to the Service:

 * The URL that the Pulumi CLI uses to connect to the Service is `https://api.pulumi.com`. (It does not use `https://app.pulumi.com`, so if you want to view the console, you'll need enable that as well.)
 * All access goes over HTTP via port 443.
```

2022-01-22 00:10 UTC, cnunciato commented on themes/default/content/docs/troubleshooting/_index.md
> +All access goes over HTTPS via port 443.
If your network blocks external traffic and you're using the Pulumi Service to manage your state, your security team may need the following details to allow the Pulumi CLI to connect to the Service:

 * The URL that the Pulumi CLI uses to connect to the Service is `https://api.pulumi.com`. (It does not use `https://app.pulumi.com`, so if you want to view the console, you'll need enable that as well.)
 * All access goes over HTTP via port 443.

2022-01-22 00:11 UTC, cnunciato requested changes
Let's try this again. 🤞

2022-01-22 00:11 UTC, cnunciato commented on themes/default/content/docs/troubleshooting/_index.md
> +All access goes over HTTPS via port 443.
If your network blocks external traffic and you're using the Pulumi Service to manage your state, your security team may need the following details to allow the Pulumi CLI to connect to the Service:

 * The URL that the Pulumi CLI uses to connect to the Service is `https://api.pulumi.com`. (It does not use `https://app.pulumi.com`, so if you want to view the console, you'll need enable that as well.)
 * All access goes over HTTP via port 443.

2022-01-22 00:13 UTC, cnunciato commented on themes/default/content/docs/troubleshooting/_index.md
> +All access goes over HTTPS via port 443.
```suggestion
If your network blocks external traffic and you're using the Pulumi Service to manage your state, your security team may need the following details to allow the Pulumi CLI to connect to the Service:

 * The URL that the Pulumi CLI uses to connect to the Service is `https://api.pulumi.com`. (It does not use `https://app.pulumi.com`, so if you want to view the console, you'll need enable that as well.)
 * All access goes over HTTP via port 443.
```

2022-01-22 09:49 UTC, susanev commented on themes/default/content/docs/troubleshooting/_index.md
> + * All access goes over HTTPS via port 443.
```suggestion
* The URL that the Pulumi CLI uses to connect to the Service is `https://api.pulumi.com`. (It does not use `https://app.pulumi.com`, so if you want to view the console, you'll need enable that as well.)
* All access goes over HTTPS via port 443.
```

2022-01-22 19:35 UTC, cnunciato approved these changes

2022-01-22 19:35 UTC, merged